<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/80x15.png" /></a><div align="center">This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.</div>

---

## Exercise 3.A

Write a function `avg(a)` that takes an array `a` of numbers and returns their mean value.

In [2]:
# your solution here

avg (generic function with 1 method)

If your solution is correct, evaluating the following cell should produce `2` as output:

In [3]:
avg([1, 2, 3])

2.0

----

## Exercise 3.B

Write a function `tr(m)` which, given a
(square) matrix `m`, returns its trace, i.e., sum of the
elements along the main diagonal.

In [4]:
# your solution here

tr (generic function with 1 method)

If your function is correct, evaluating the following cell should produce `3` as output:

In [6]:
tr(ones(3,3))

3.0

----

## Exercise 3.C

Write a function `eye(n)` which, given
an integer $n > 0$, returns the $n × n$ identity matrix.

In [7]:
# your solution here

eye (generic function with 1 method)

If your solution is correct, evaluating the following cell should produce a 3x3 array with ones on the diagonal:

In [8]:
eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

----

## Exercise 3.D

Write a function `flip(m)` which, given
a matrix `m`, returns its transpose.

In [14]:
# your solution here

flip (generic function with 1 method)

Check if your solution is correct by applying it to the matrix `m = [1 2; 3 4]`:

In [15]:
flip([1 2; 3 4])

2×2 Array{Float64,2}:
 1.0  3.0
 2.0  4.0

You can use the built-in macro `@time` to compare this hand-rolled solution to the built-in `transpose()`function:

In [19]:
m = randn((10000, 10000));

In [22]:
@time flip(m);

  4.928881 seconds (6 allocations: 762.940 MiB, 1.36% gc time)


In [23]:
@time transpose(m);

  0.000004 seconds (5 allocations: 176 bytes)


----

## Exercise 3.E

Write a function `median(v)` that takes a vector `v` of numbers, and returns the median value.

In [26]:
# your solution here

median (generic function with 1 method)

If your solution is correct, evaluating the following cell should produce `2` as output:

In [27]:
median([1, 7, 2, 2, 2, 3, 2])

2

A correct solution would evaluate the following cell to `4`:

In [28]:
median([1, 3, 5, 7])

2.0

----

## Exercise 3.F

Write a function `evens(v)` that takes a vector of integers and returns a list of all the even ones.

Recall that:
* the `%` operator is used for computing the remainder of integer division;
* the `push!()` function is used to append an element to a list

In [40]:
# your solution here

evens (generic function with 1 method)

If your solution is correct, evaluating the following cell should produce `[1, 3]` as output:

In [41]:
evens([1,2,3])

2-element Array{Int64,1}:
 1
 3

----

## Exercise 3.G

Write a function `deviation(v, u)` that takes a vector `v` of
numbers and a single value `u` returns a list with the 
absolute value of the difference $|x-u|$
for each element `x` of `v`.

In [38]:
# your solution here

deviation (generic function with 1 method)

If your solution is correct, evaluating the following cell should produce `[1, 0, 1]` as output:

In [39]:
deviation([1,2,3], 2)

3-element Array{Int64,1}:
 1
 0
 1